[package]
name = "iso2god"
version = "1.4.6"
description = "A tool to convert between Xbox 360 ISO and Games On Demand file formats"
repository = "https://github.com/iliazeus/iso2god-rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
bitflags = "2.2.1"
byteorder = "1.4.3"
clap = { version = "4.2.5", features = ["derive"] }
hex = "0.4.3"
num = "0.4.0"
reqwest = { version = "0.11.17", features = ["blocking", "json"] }
serde = { version = "1.0.160", features = ["derive"] }
serde-aux = "4.2.0"
serde_json = "1.0.96"
sha1 = "0.10.5"

[profile.release]
strip = true
lto = true
