[package]
name = "iso2god"
version = "1.4.1"
description = "A tool to convert between Xbox 360 ISO and Games On Demand file formats"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.59", features = ["backtrace"] }
bitflags = "1.3.2"
byteorder = "1.4.3"
clap = { version = "3.2.16", features = ["derive"] }
hex = "0.4.3"
num = "0.4.0"
sha1 = "0.10.1"
