[package]
name = "iso2god"
version = "1.4.4"
description = "A tool to convert between Xbox 360 ISO and Games On Demand file formats"
repository = "https://github.com/iliazeus/iso2god-rs"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.59", features = ["backtrace"] }
bitflags = "1.3.2"
byteorder = "1.4.3"
clap = { version = "3.2.16", features = ["derive"] }
hex = "0.4.3"
num = "0.4.0"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
serde = { version = "1.0.141", features = ["derive"] }
serde-aux = "3.1.0"
serde_json = "1.0.82"
sha1 = "0.10.1"

[profile.release]
strip = true
lto = true
