name: Release

on:
  push:
    tags:
      - v*
    branches:
      - ci-*
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-to-github:
    name: Build
    runs-on: ${{matrix.runner}}

    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            rust: nightly
            target: x86_64-unknown-linux-gnu
            filename: iso2god-x86_64-linux

          - runner: macos-12
            rust: nightly
            target: x86_64-apple-darwin
            filename: iso2god-x86_64-macos

          - runner: macos-14
            rust: nightly
            target: aarch64-apple-darwin
            filename: iso2god-aarch64-macos

          - runner: windows-latest
            rust: nightly
            target: x86_64-pc-windows-gnu
            filename: iso2god-x86_64-windows.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
            target
          key: ${{ matrix.rust }}-${{ matrix.target }}

      - name: Install Rust
        run: |
          rustup default ${{ matrix.rust }}
          rustup target add ${{ matrix.target }}
          rustup show

      - name: Build
        run: |
          cargo build -Z unstable-options --release --target ${{ matrix.target }} --bin iso2god --artifact-dir out
          mv out/* out/${{ matrix.filename }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          draft: ${{ github.ref_type != 'tag' || !startsWith(github.ref_name, 'v') }}
          files: out/*
          fail_on_unmatched_files: false
